### ISSUE TITLE
TagName not found

### ISSUE THREAD

**Issue by GetAlice** [byronka/minum_usage_example_smaller#2]
When I follow doc 'getting_started_part_3.md'  [Step 1 - Adding a Test], I can not found com.renomad.minum.htmlparsing.TagName.  in External libraries , show like this 
![image](https://github.com/byronka/minum_usage_example_smaller/assets/38805704/ab5d3422-36c4-48fc-9985-e298101246f1)

**Comment by byronka** [comment]
Hmm.  Let me look into that.

**Comment by byronka** [comment]
While I'm looking, mind letting me know what version of Java are you running?  Try these commands from your command line in intellij.  These will get the version of the java virtual machine and the java compiler.
java -version 
javac -version

**Comment by byronka** [comment]
I took a look. I do not see any obvious reason why there would be an issue with that file - it is a regular Java enum, not even using recent Java features.  The first thing I would do in your situation is to [restart Intellij with invalidated cache](https://www.jetbrains.com/help/idea/invalidate-caches.html).  Then, if that does not fix it, I would delete Minum from the Maven cache (following are instructions for deleting it on the command line, assuming you are using a unix-like system like Mac or Cygwin):

```shell
# change directory to where Minum is cached
cd ~/.m2/repository/com/renomad/minum/
# list files in the directory
ls 
# Remove the 2.2.1 version
rm -fr 2.2.1
```

After that, the system will have to download the framework again - maybe there was a corrupted file?

Also, it may help if you try running and examining the [finished project](https://github.com/byronka/minum_getting_started_code) for the getting started documentation
